### ISSUE TITLE
Sprint 6 nlp/cancer.owl will not load

### ISSUE THREAD

**Issue by seanfinan** [DeepPhe/DeepPhe#15]
The sprint 6 nlp Ontology doesn't load.
I think that I tracked it down to a circular import.
    <Import>http://blulab.chpc.utah.edu/ontologies/v2/SchemaOntology.owl</Import>
    <Import>http://ontologies.dbmi.pitt.edu/deepphe/cancer/cancer.owl</Import>
    <Annotation>
I think that the fix is to import Terminology.owl as did the Sprint 5 version.
    <Import>http://blulab.chpc.utah.edu/ontologies/v2/SchemaOntology.owl</Import>
    <Import>http://blulab.chpc.utah.edu/ontologies/Terminology.owl</Import>
    <Annotation>

**Comment by mecst76** [comment]
I tried opening the ontologies using Protege from the files contained in the release as well as opening them from their URIs. I don't have any problems loading any of them. Can you give me the exact error that you're receiving from either Protege or java so that I can track down the problem?

**Comment by seanfinan** [comment]
The problem might be having .../cancer.owl and .../nlp/cancer.owl imports when local versions are required.  Is there another way to name these?  .../cancer.owl and .../nlp_cancer.owl ?  Or am I breaking a convention?

**Comment by tseytlin** [comment]
If you import the ontologies via Noble api then this should be taken care
of. I'll try to replicate the issue tomorrow
