### ISSUE TITLE
DegreOfTextRelation Modifer has incorrect span.

### ISSUE THREAD

**Issue by tseytlin** [DeepPhe/DeepPhe#19]
In demo doc2 in DegreeOfTextRelation PR-neg, is annotated as PR -> mapping to SignSymptom and -neg or neg should map to Negative. Instead the - (hyphen) is mapped to Negative.

This looks like a simple span issue for the Modifier of ReceptorStatus

**Comment by seanfinan** [comment]
Fixed, tested, checked in.  Regex could use a unit test, but expedited for Eugene
